# Site settings
keywords: Data Science, Statistics
author: Willian Werner
source: .
destination: _site
baseurl: ""
url: "https://willianw.github.io"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /:year/:short_month/:title

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: category
      permalink: /category/:title