# Site settings
title: Beyond Similarity
description: Willian Werner's personal blog
keywords: Data Science, Statistics
author: Willian Werner
source: .
destination: _site
baseurl: ""
url: "https://willianw.github.io"
